categories: [Metabolomics]
description: '[W4M][Metabolomics][LC-MS] HMDB database MS Search Package - Annotation - Returns
  annotation results (adducts and metabolites) from The Human Metabolome Database.'
homepage_url: http://workflow4metabolomics.org
long_description: 'Part of the W4M project: http://workflow4metabolomics.org / HMDB:
  http://www.hmdb.ca/. The wrapper script use the HMDB ''MS search'' resource to annotate
  a list of m/z. The process returns outputs files (CSV and HTML formats) with links
  through metabocards.'
name: hmdb_ms_search
owner: fgiacomoni
